server:
  port: 8081

jasypt:
  encryptor:
    password: abc

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  # mysql配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?noAccessToProcedureBodies=true&zeroDateTimeBehavior=round&connectTimeout=10000&socketTimeout=60000&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=TRUE&useSSL=false
    username: ENC(sQVyWjOwOZuEpJG4nzloZg==)
    password: ENC(sQVyWjOwOZuEpJG4nzloZg==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1765000
      maximumPoolSize: 15
      connection-timeout: 60000
#缓存配置
  cache:
      type: redis
  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
    cluster:
      nodes: tencent2:7000,tencent2:7001,tencent2:7002,tencent2:7003,tencent2:7004,tencent2:7005
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 3600
# 消息中间件
  rocketmq:
    name-server-address: 172.21.10.111:9876
    # 可选, 如果无需发送消息则忽略该配置
    producer-group: local_pufang_producer
    # 发送超时配置毫秒数, 可选, 默认3000
    send-msg-timeout: 5000
    # 追溯消息具体消费情况的开关，默认打开
    trace-enabled: false
    # 是否启用VIP通道，默认打开
    vip-channel-enabled: false


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

logback:
  file: "~/logs"